apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-app
  ports:
    - port: 8090
      targetPort: 8090
  clusterIP: 10.96.1.33
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: okhotnik/spring-boot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
          - name: SPRING_DATA_MONGODB_URI
            value: "mongodb://10.96.1.31:27017/springdb"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://10.96.1.32:3306/strdb"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "Okhotnik"